---
# Blue Version
apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-service-blue
  namespace: lugx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: game-service
      version: blue
  template:
    metadata:
      labels:
        app: game-service
        version: blue
    spec:
      containers:
      - name: game-service
        image: thaksha98/lugx-game-service:blue
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "128Mi"
            cpu: "200m"
          limits:
            memory: "256Mi"
            cpu: "400m"
---
# Green Version
apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-service-green
  namespace: lugx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: game-service
      version: green
  template:
    metadata:
      labels:
        app: game-service
        version: green
    spec:
      containers:
      - name: game-service
        image: thaksha98/lugx-game-service:green
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "128Mi"
            cpu: "200m"
          limits:
            memory: "256Mi"
            cpu: "400m"
---
# Stable Service (routes traffic to current active version)
apiVersion: v1
kind: Service
metadata:
  name: game-service
  namespace: lugx
  labels:
    app: game-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: game-service
    version: blue   # 👉 Initially points to Blue
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
