name: Blue-Green Deploy

on:
  push:
    branches: [ main ]

env:
  IMAGE: rakavan/lugx-frontend
  TAG: v${{ github.run_number }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-qemu-action@v2
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: rakavan
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Frontend
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ${{ env.IMAGE }}:${{ env.TAG }}

    - name: Deploy to Kubernetes
      run: |
        sed -i "s|image:.*|image: ${IMAGE}:${TAG}|" manifests/frontend-deployment.yaml
        kubectl apply -f manifests/frontend-deployment.yaml
        kubectl rollout status deployment/frontend-deployment -n lugx

    - name: Run Integration Tests
      run: |
        python3 tests/test_api.py
