name: Blue-Green CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  # --- Job 1: Determine Blue or Green based on run number ---
  determine-color:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.set-color.outputs.new_color }}
      old_version: ${{ steps.set-color.outputs.old_color }}
    steps:
      - id: set-color
        run: |
          run_num=${{ github.run_number }}
          if (( run_num % 2 == 0 )); then
            echo "new_color=blue" >> $GITHUB_OUTPUT
            echo "old_color=green" >> $GITHUB_OUTPUT
          else
            echo "new_color=green" >> $GITHUB_OUTPUT
            echo "old_color=blue" >> $GITHUB_OUTPUT
          fi

  # --- Job 2: Deploy (depends on determine-color) ---
  deploy:
    needs: determine-color
    runs-on: ubuntu-latest
    env:
      NEW_VERSION: ${{ needs.determine-color.outputs.new_version }}
      OLD_VERSION: ${{ needs.determine-color.outputs.old_version }}
      DOCKER_REPO: thaksha98
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # ─────────────────────────────────────────────────────────────
      # 🔵🟢 Build and Push Images
      # ─────────────────────────────────────────────────────────────
      - name: Build and Push Frontend (${{ env.NEW_VERSION }})
        uses: docker/build-push-action@v5
        with:
          context: frontend
          file: frontend/Dockerfile
          push: true
          tags: ${{ env.DOCKER_REPO }}/lugx-frontend:${{ env.NEW_VERSION }}

      - name: Build and Push Game Service (${{ env.NEW_VERSION }})
        uses: docker/build-push-action@v5
        with:
          context: .
          file: backend/game-service/Dockerfile
          push: true
          tags: ${{ env.DOCKER_REPO }}/lugx-game-service:${{ env.NEW_VERSION }}

      - name: Build and Push Order Service (${{ env.NEW_VERSION }})
        uses: docker/build-push-action@v5
        with:
          context: .
          file: backend/order-service/Dockerfile
          push: true
          tags: ${{ env.DOCKER_REPO }}/lugx-order-service:${{ env.NEW_VERSION }}


      - name: Build and Push Analytics Service (${{ env.NEW_VERSION }})
        uses: docker/build-push-action@v5
        with:
          context: .
          file: backend/analytics-service/Dockerfile
          push: true
          tags: ${{ env.DOCKER_REPO }}/lugx-analytics-service:${{ env.NEW_VERSION }}


      # ─────────────────────────────────────────────────────────────
      # ☸️ Deploy to Kubernetes
      # ─────────────────────────────────────────────────────────────
      - name: Deploy New Version to Kubernetes
        env:
          KUBECONFIG_DATA: ${{ secrets.KUBE_CONFIG }}
        run: |
          echo "$KUBECONFIG_DATA" | base64 -d > ./kubeconfig
          export KUBECONFIG=./kubeconfig

          kubectl set image deployment/frontend-deployment-${{ env.NEW_VERSION }}   frontend=${{ env.DOCKER_REPO }}/lugx-frontend:${{ env.NEW_VERSION }}   -n lugx
          kubectl set image deployment/game-service-${{ env.NEW_VERSION }}         game-service=${{ env.DOCKER_REPO }}/lugx-game-service:${{ env.NEW_VERSION }}         -n lugx
          kubectl set image deployment/order-service-${{ env.NEW_VERSION }}        order-service=${{ env.DOCKER_REPO }}/lugx-order-service:${{ env.NEW_VERSION }}        -n lugx
          kubectl set image deployment/analytics-service-${{ env.NEW_VERSION }}    analytics-service=${{ env.DOCKER_REPO }}/lugx-analytics-service:${{ env.NEW_VERSION }}    -n lugx

          kubectl rollout status deployment/frontend-deployment-${{ env.NEW_VERSION }}   -n lugx --timeout=60s
          kubectl rollout status deployment/game-service-${{ env.NEW_VERSION }}         -n lugx --timeout=60s
          kubectl rollout status deployment/order-service-${{ env.NEW_VERSION }}        -n lugx --timeout=60s
          kubectl rollout status deployment/analytics-service-${{ env.NEW_VERSION }}    -n lugx --timeout=60s

      # ─────────────────────────────────────────────────────────────
      # 🧪 Run Integration Tests
      # ─────────────────────────────────────────────────────────────
      - name: Run Integration Tests
        run: |
          python3 tests/test_api.py --target ${{ env.NEW_VERSION }} --base-url http://192.168.8.240

      # ─────────────────────────────────────────────────────────────
      # 🚦 Switch Traffic to New Version
      # ─────────────────────────────────────────────────────────────
      - name: Switch Services to ${{ env.NEW_VERSION }}
        env:
          KUBECONFIG_DATA: ${{ secrets.KUBE_CONFIG }}
        run: |
          echo "$KUBECONFIG_DATA" | base64 -d > ./kubeconfig
          export KUBECONFIG=./kubeconfig

          kubectl patch service frontend-service     -n lugx -p '{"spec":{"selector":{"version":"${{ env.NEW_VERSION }}"}}}'
          kubectl patch service game-service         -n lugx -p '{"spec":{"selector":{"version":"${{ env.NEW_VERSION }}"}}}'
          kubectl patch service order-service        -n lugx -p '{"spec":{"selector":{"version":"${{ env.NEW_VERSION }}"}}}'
          kubectl patch service analytics-service    -n lugx -p '{"spec":{"selector":{"version":"${{ env.NEW_VERSION }}"}}}'

          echo "✅ Traffic switched to ${{ env.NEW_VERSION }}"

      # ─────────────────────────────────────────────────────────────
      # 🗑️ Scale Down Old Version
      # ─────────────────────────────────────────────────────────────
      - name: Scale Down Old Version
        env:
          KUBECONFIG_DATA: ${{ secrets.KUBE_CONFIG }}
        run: |
          echo "$KUBECONFIG_DATA" | base64 -d > ./kubeconfig
          export KUBECONFIG=./kubeconfig

          kubectl scale deployment frontend-deployment-${{ env.OLD_VERSION }}   --replicas=0 -n lugx
          kubectl scale deployment game-service-${{ env.OLD_VERSION }}         --replicas=0 -n lugx
          kubectl scale deployment order-service-${{ env.OLD_VERSION }}        --replicas=0 -n lugx
          kubectl scale deployment analytics-service-${{ env.OLD_VERSION }}    --replicas=0 -n lugx

          echo "🗑️ Old (${{ env.OLD_VERSION }}) deployments scaled down"
