name: Lugx Gaming CI/CD Pipeline (Optimized)

on:
  push:
    branches: [ main ]

env:
  DOCKER_REPO: thaksha98
  KUBE_NAMESPACE: lugx
  GIT_SHA: ${{ github.sha }}

jobs:
  determine-color:
    runs-on: self-hosted
    outputs:
      new_version: ${{ steps.set-color.outputs.new_color }}
      old_version: ${{ steps.set-color.outputs.old_color }}
    steps:
      - id: set-color
        run: |
          run_num=${{ github.run_number }}
          if (( run_num % 2 == 0 )); then
            echo "new_color=blue" >> $GITHUB_OUTPUT
            echo "old_color=green" >> $GITHUB_OUTPUT
          else
            echo "new_color=green" >> $GITHUB_OUTPUT
            echo "old_color=blue" >> $GITHUB_OUTPUT
          fi

  deploy:
    needs: determine-color
    runs-on: self-hosted
    env:
      NEW_VERSION: ${{ needs.determine-color.outputs.new_version }}
      OLD_VERSION: ${{ needs.determine-color.outputs.old_version }}
      DOCKER_REPO: thaksha98
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and Push Frontend
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/lugx-frontend:${{ needs.determine-color.outputs.new_version }} frontend/
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/lugx-frontend:${{ needs.determine-color.outputs.new_version }}

      - name: Build and Push Game Service
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/lugx-game-service:${{ needs.determine-color.outputs.new_version }} backend/game-service/
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/lugx-game-service:${{ needs.determine-color.outputs.new_version }}

      - name: Build and Push Order Service
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/lugx-order-service:${{ needs.determine-color.outputs.new_version }} backend/order-service/
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/lugx-order-service:${{ needs.determine-color.outputs.new_version }}

      - name: Build and Push Analytics Service
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/lugx-analytics-service:${{ needs.determine-color.outputs.new_version }} backend/analytics-service/
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/lugx-analytics-service:${{ needs.determine-color.outputs.new_version }}

      - name: Configure KUBECONFIG
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Deploy & Switch Traffic
        run: |
          export NS=lugx
          export NEW_COLOR=${{ needs.determine-color.outputs.new_version }}
          export OLD_COLOR=${{ needs.determine-color.outputs.old_version }}
          export DOCKER_REPO=${{ secrets.DOCKERHUB_USERNAME }}

          # Update new deployments
          kubectl set image deployment/frontend-deployment-$NEW_COLOR   frontend=$DOCKER_REPO/lugx-frontend:$NEW_COLOR   -n $NS
          kubectl set image deployment/game-service-$NEW_COLOR         game-service=$DOCKER_REPO/lugx-game-service:$NEW_COLOR         -n $NS
          kubectl set image deployment/order-service-$NEW_COLOR        order-service=$DOCKER_REPO/lugx-order-service:$NEW_COLOR        -n $NS
          kubectl set image deployment/analytics-service-$NEW_COLOR    analytics-service=$DOCKER_REPO/lugx-analytics-service:$NEW_COLOR    -n $NS

          # Wait for rollouts with retries
          for i in {1..3}; do
            echo "Attempt $i: Waiting for rollouts..."
            kubectl rollout status deployment/frontend-deployment-$NEW_COLOR   -n $NS --timeout=180s || continue
            kubectl rollout status deployment/game-service-$NEW_COLOR         -n $NS --timeout=180s || continue
            kubectl rollout status deployment/order-service-$NEW_COLOR        -n $NS --timeout=180s || continue
            kubectl rollout status deployment/analytics-service-$NEW_COLOR    -n $NS --timeout=180s || continue
            break
          done

          # If all attempts fail, exit with error
          if [ $i -eq 3 ]; then
            echo "❌ Rollout failed after 3 attempts"
            exit 1
          fi

          # Switch traffic
          kubectl patch service frontend-service     -n $NS -p "{\"spec\":{\"selector\":{\"version\":\"$NEW_COLOR\"}}}"
          kubectl patch service game-service         -n $NS -p "{\"spec\":{\"selector\":{\"version\":\"$NEW_COLOR\"}}}"
          kubectl patch service order-service        -n $NS -p "{\"spec\":{\"selector\":{\"version\":\"$NEW_COLOR\"}}}"
          kubectl patch service analytics-service    -n $NS -p "{\"spec\":{\"selector\":{\"version\":\"$NEW_COLOR\"}}}"

          echo "✅ Traffic switched to $NEW_COLOR"

          # Scale down old (only if old_color is not empty)
          if [ -n "$OLD_COLOR" ] && [ "$OLD_COLOR" != " " ]; then
            kubectl scale deployment frontend-deployment-$OLD_COLOR --replicas=0 -n $NS
            kubectl scale deployment game-service-$OLD_COLOR --replicas=0 -n $NS
            kubectl scale deployment order-service-$OLD_COLOR --replicas=0 -n $NS
            kubectl scale deployment analytics-service-$OLD_COLOR --replicas=0 -n $NS
            echo "🗑️ Old ($OLD_COLOR) deployments scaled down"
          else
            echo "🟡 First deploy — no old version to scale down"
          fi

      - name: Run Integration Tests
        run: |
          python3 tests/test_api.py --target $NEW_COLOR --base-url http://192.168.8.240
